services:
  todo-list-service:
    build: .
    container_name: todo-list-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SCHEDULER_TODO_PAST_DUE_ENABLED: "true"
      SCHEDULER_TODO_PAST_DUE_INTERVAL_MS: "30000"
    restart: unless-stopped